# Generated by Django 4.1.7 on 2023-03-07 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="images",
            name="image",
        ),
        migrations.AddField(
            model_name="images",
            name="images",
            field=models.FileField(
                default="",
                upload_to="media/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "img", "jpg", "jpeg"]
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="images",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
