# Generated by Django 4.1.7 on 2023-03-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0002_remove_images_image_images_images_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="region",
        ),
        migrations.AddField(
            model_name="tour",
            name="region",
            field=models.ManyToManyField(related_name="tour_region", to="tour.region"),
        ),
    ]
