# Generated by Django 4.1.7 on 2023-03-07 14:34

import django.core.validators
from django.db import migrations, models
import src.users.utils


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0003_remove_tour_region_tour_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="images",
            field=models.FileField(
                upload_to=src.users.utils.path_and_rename,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "img", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
    ]
