# Generated by Django 4.1.7 on 2023-03-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0004_alter_images_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialists", models.PositiveSmallIntegerField()),
                ("clients", models.PositiveSmallIntegerField()),
                ("tours", models.PositiveSmallIntegerField()),
                ("years", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
