# Generated by Django 4.1.7 on 2023-03-13 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0006_alter_aboutus_options_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
