# Generated by Django 4.1.7 on 2023-03-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0007_delete_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="qr_code",
            field=models.CharField(default="", max_length=8),
        ),
    ]
