# Generated by Django 4.1.7 on 2023-03-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0011_remove_tour_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="qr_code",
            field=models.CharField(blank=True, default="", max_length=8, null=True),
        ),
    ]
