version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ulul1_web
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic
        --no-input && gunicorn -b 0.0.0.0:8088 core.wsgi --reload"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8088
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: ulul1_db
    restart: always
    ports:
      - '5535:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - '8880:80'
      - '443:443'
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: