# Generated by Django 4.1.6 on 2023-02-09 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaceFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=25)),
                ('name_place', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=25)),
                ('name_place', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('date_publishied', models.DateField()),
                ('date_departure', models.DateTimeField()),
                ('date_arrival', models.DateTimeField()),
                ('quantity_limit', models.PositiveIntegerField()),
                ('actual_limit', models.PositiveIntegerField()),
                ('is_hot', models.BooleanField(default=False, null=True)),
                ('duration_field', models.CharField(choices=[('1', 'День'), ('3', '3 дня'), ('7', 'Неделя')], max_length=30)),
                ('complexity', models.CharField(choices=[('Easy', 'Легкий'), ('Meduim', 'Средний'), ('Hard', 'Сложный'), ('Extra', 'Экстра-сложный')], max_length=30)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.category')),
                ('from_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.placefrom')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.placeto')),
            ],
        ),
    ]
