# Generated by Django 4.1.6 on 2023-02-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='actual_limit',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.category'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_publishied',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tour',
            name='quantity_limit',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
