# Generated by Django 4.1.6 on 2023-02-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_alter_category_image_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'Изображение туров',
                'verbose_name_plural': 'Изображения туров',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=255, verbose_name='Название города')),
                ('name_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Конкретное место')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='date_publishied',
            new_name='date_published',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='duration_field',
        ),
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.CharField(choices=[('1', 'День'), ('3', '3 дня'), ('7', 'Неделя')], default='День', max_length=30, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='complexity',
            field=models.CharField(choices=[('Easy', 'Легкий'), ('Medium', 'Средний'), ('Hard', 'Сложный'), ('Extra', 'Экстра-сложный')], max_length=30, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_arrival',
            field=models.DateTimeField(verbose_name='Дата и время приезда'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_departure',
            field=models.DateTimeField(verbose_name='Дата и время выезда'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='Описание тура'),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='image',
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_hot',
            field=models.BooleanField(default=False, null=True, verbose_name='Является горячим'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='quantity_limit',
            field=models.PositiveIntegerField(blank=True, verbose_name='Лимит'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Название тура'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='from_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_place', to='tour.place', verbose_name='Откуда'),
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='image_of_tour', to='tour.images'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='tour.place', verbose_name='Куда'),
        ),
        migrations.DeleteModel(
            name='PlaceFrom',
        ),
        migrations.DeleteModel(
            name='PlaceTo',
        ),
    ]
