# Generated by Django 4.1.6 on 2023-02-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_images_place_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Изображения тура'),
        ),
    ]
