# Generated by Django 4.1.6 on 2023-02-10 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.tour'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Изображение тура'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='image_of_tour', to='tour.images', verbose_name='Изображения'),
        ),
    ]
