# Generated by Django 4.1.6 on 2023-02-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_images_tour_alter_images_image_alter_tour_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='image',
        ),
        migrations.AlterField(
            model_name='tour',
            name='actual_limit',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
