# Generated by Django 4.1.6 on 2023-02-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_remove_tour_image_alter_tour_actual_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='image_of_tour', to='tour.images', verbose_name='Изображения'),
        ),
    ]
