# Generated by Django 4.1.7 on 2023-02-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='slug',
            new_name='user_slug',
        ),
    ]
