# Generated by Django 4.1.7 on 2023-03-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_rename_slug_user_user_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
