# Generated by Django 4.1.7 on 2023-03-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
        migrations.RemoveField(
            model_name="user",
            name="number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_slug",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
