# Generated by Django 4.1.7 on 2023-03-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0004_alter_images_images"),
        ("users", "0007_rename_name_user_last_name_remove_user_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_tour",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="favorite_tour",
                to="tour.tour",
                verbose_name="Избранные",
            ),
        ),
    ]
