# Generated by Django 4.1.7 on 2023-03-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0004_alter_images_images"),
        ("users", "0008_user_favorite_tour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favorite_tour",
            field=models.ManyToManyField(
                related_name="favorite_tour", to="tour.tour", verbose_name="Избранные"
            ),
        ),
    ]
