# Generated by Django 4.1.7 on 2023-03-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_favorite_tour"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True, default="", max_length=50, unique=True
            ),
            preserve_default=False,
        ),
    ]
