# Generated by Django 4.1.7 on 2023-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_rename_first_name_user_name_remove_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
