# Generated by Django 4.1.7 on 2023-03-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_rename_first_name_user_name_remove_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=True, help_text="Email activated"),
        ),
    ]
