# Generated by Django 4.1.7 on 2023-03-16 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_username"),
        ("users", "0012_alter_user_is_active_alter_user_is_verified"),
    ]

    operations = []
