# Generated by Django 4.1.7 on 2023-03-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_merge_20230316_1356"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
