# Generated by Django 4.1.7 on 2023-02-19 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('rate', models.IntegerField(blank=True, choices=[('⭐', '1'), ('⭐⭐', '2'), ('⭐⭐⭐', '3'), ('⭐⭐⭐⭐', '4'), ('⭐⭐⭐⭐⭐', '5')], default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
