# Generated by Django 4.1.7 on 2023-02-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_basemodel_remove_userreview_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='user',
        ),
    ]
