# Generated by Django 4.1.7 on 2023-02-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_remove_userreview_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreview",
            name="user",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
