# Generated by Django 4.1.7 on 2023-03-03 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_userreview_slug_alter_userreview_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userreview",
            name="basemodel_ptr",
        ),
        migrations.RemoveField(
            model_name="userreview",
            name="user",
        ),
        migrations.DeleteModel(
            name="BaseModel",
        ),
        migrations.DeleteModel(
            name="UserReview",
        ),
    ]
