# Generated by Django 4.1.6 on 2023-02-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.avatar'),
        ),
    ]
