# Generated by Django 4.1.6 on 2023-02-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_avatar_image_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name': 'Аватар', 'verbose_name_plural': 'Аватары'},
        ),
    ]
